# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Govida"
license = "MIT"
licenselink = "https://github.com/viirak/govida/blob/master/LICENSE"
description = ""
homepage = "https://viirak.com/"
tags = ["Responsive"]
features = []
min_version = "0.1.0"

[author]
  name = "Virak HOR"
  homepage = "https://viirak.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
